# general settings
name: train_CAR_CAT_q20
model_type: CATModel
scale: 1
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: CAR
    name: DFWB
    type: PairedImageDataset
    dataroot_gt: datasets/DFWB/HQ
    dataroot_lq: datasets/DFWB/LQ/20
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 16
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: CAR
    name: Classic5
    type: PairedImageDataset
    dataroot_gt: datasets/CAR/classic5/Classic5_HQ
    dataroot_lq: datasets/CAR/classic5/Classic5_LQ/20
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: CAT
  upscale: 1
  in_chans: 1
  img_size: 128
  split_size_0: [2,2,2,4,4,4]
  split_size_1: [0,0,0,0,0,0] # The other side is H or W
  img_range: 255.
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  mlp_ratio: 4
  resi_connection: '1conv'
  block_name: 'CATB_axial'

# path
path:
  pretrain_network_g: experiments/pretrained_models/CAR/CAR_CAT_q40.pth
  strict_load_g: True
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4 # for jpeg 10/20/30
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 400000, 600000, 700000, 750000 ] # for jpeg 10/20/30
    gamma: 0.5

  total_iter: 800000 # for jpeg 10/20/30
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-3

# validation settings
val:
  val_freq: !!float 5e3
  save_img: False
  use_chop: True

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
